Changed to build on msys/mingw and Unix. Sign manifest.

diff --git a/tdbcmysql/configure b/tdbcmysql/configure
--- a/tdbcmysql/configure
+++ b/tdbcmysql/configure
@@ -7829,6 +7829,13 @@ fi
 CLEANFILES="$CLEANFILES pkgIndex.tcl"
 
 
+if test "${TEA_PLATFORM}" = "windows" ; then
+    cat >>confdefs.h <<\_ACEOF
+#define _WIN32 1
+_ACEOF
+
+fi
+
 #--------------------------------------------------------------------
 # Choose which headers you need.  Extension authors should try very
 # hard to only rely on the Tcl public header files.  Internal headers
@@ -11762,20 +11769,27 @@ if test "${with_mysql_includedir+set}" = set; then
 fi;
 if test x"${with_mysqlincludedir}" != x ; then
     CPPFLAGS="${CPPFLAGS} -I${with_mysqlincludedir}"
+    if test "${TEA_PLATFORM}" = "windows" ; then
+        CPPFLAGS="${CPPFLAGS} -D_WIN32"
+    fi
     MYSQL_INCLUDE_SPEC="-I${with_mysqlincludedir}"
 fi
-if test "${ac_cv_header_mysql_h+set}" = set; then
-  echo "$as_me:$LINENO: checking for mysql.h" >&5
-echo $ECHO_N "checking for mysql.h... $ECHO_C" >&6
-if test "${ac_cv_header_mysql_h+set}" = set; then
+
+for ac_header in my_global.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 fi
-echo "$as_me:$LINENO: result: $ac_cv_header_mysql_h" >&5
-echo "${ECHO_T}$ac_cv_header_mysql_h" >&6
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
 else
   # Is the header compilable?
-echo "$as_me:$LINENO: checking mysql.h usability" >&5
-echo $ECHO_N "checking mysql.h usability... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -11783,7 +11797,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 $ac_includes_default
-#include <mysql.h>
+#include <$ac_header>
 _ACEOF
 rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
@@ -11819,15 +11833,15 @@ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
 echo "${ECHO_T}$ac_header_compiler" >&6
 
 # Is the header present?
-echo "$as_me:$LINENO: checking mysql.h presence" >&5
-echo $ECHO_N "checking mysql.h presence... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <mysql.h>
+#include <$ac_header>
 _ACEOF
 if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
@@ -11861,25 +11875,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6
 # So?  What about this header?
 case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
   yes:no: )
-    { echo "$as_me:$LINENO: WARNING: mysql.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: mysql.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: mysql.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: mysql.h: proceeding with the compiler's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
     ac_header_preproc=yes
     ;;
   no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: mysql.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: mysql.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: mysql.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: mysql.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: mysql.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: mysql.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: mysql.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: mysql.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: mysql.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: mysql.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: mysql.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: mysql.h: in the future, the compiler will take precedence" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
     (
       cat <<\_ASBOX
 ## ------------------------------------ ##
@@ -11890,17 +11904,79 @@ _ASBOX
       sed "s/^/$as_me: WARNING:     /" >&2
     ;;
 esac
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+
+done
+
 echo "$as_me:$LINENO: checking for mysql.h" >&5
 echo $ECHO_N "checking for mysql.h... $ECHO_C" >&6
 if test "${ac_cv_header_mysql_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_cv_header_mysql_h=$ac_header_preproc
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <stdio.h>
+#ifdef HAVE_MY_GLOBAL_H
+#include <my_global.h>
+#endif
+
+
+#include <mysql.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_header_mysql_h=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_header_mysql_h=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 fi
 echo "$as_me:$LINENO: result: $ac_cv_header_mysql_h" >&5
 echo "${ECHO_T}$ac_cv_header_mysql_h" >&6
-
-fi
 if test $ac_cv_header_mysql_h = yes; then
   :
 else
@@ -11923,7 +11999,6 @@ CPPFLAGS="${TDBCMYSQL_SAVED_CPPLFAGS}"
 # Locate the MySQL libraries.
 #----------------------------------------------------------------------
 
-TDBCMYSQL_SAVED_LDFLAGS="${LDFLAGS}"
 
 # Check whether --with-mysql-libdir or --without-mysql-libdir was given.
 if test "${with_mysql_libdir+set}" = set; then
@@ -11932,14 +12007,17 @@ if test "${with_mysql_libdir+set}" = set; then
 fi;
 if test x"${with_mysqllibdir}" != x ; then
   LDFLAGS="${LDFLAGS} -L${with_mysqllibdir}"
-  MYSQL_LIB_SPEC="-L${with_mysqllibdir} -lmysqlclient_r"
+  MYSQL_LIB_SPEC="-L${with_mysqllibdir}"
 else
-  MYSQL_LIB_SPEC="-lmysqlclient_r"
+  MYSQL_LIB_SPEC=""
 fi
-
-echo "$as_me:$LINENO: checking for mysql_server_init in -lmysqlclient_r" >&5
-echo $ECHO_N "checking for mysql_server_init in -lmysqlclient_r... $ECHO_C" >&6
-if test "${ac_cv_lib_mysqlclient_r_mysql_server_init+set}" = set; then
+if test "${TEA_PLATFORM}" = "windows" ; then
+      MYSQL_LIB_SPEC="-lmysql"
+else
+    TDBCMYSQL_SAVED_LDFLAGS="${LDFLAGS}"
+    echo "$as_me:$LINENO: checking for mysql_reconnect in -lmysqlclient_r" >&5
+echo $ECHO_N "checking for mysql_reconnect in -lmysqlclient_r... $ECHO_C" >&6
+if test "${ac_cv_lib_mysqlclient_r_mysql_reconnect+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
@@ -11957,11 +12035,11 @@ extern "C"
 #endif
 /* We use char because int might match the return type of a gcc2
    builtin and then its argument prototype would still apply.  */
-char mysql_server_init ();
+char mysql_reconnect ();
 int
 main ()
 {
-mysql_server_init ();
+mysql_reconnect ();
   ;
   return 0;
 }
@@ -11988,34 +12066,105 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_lib_mysqlclient_r_mysql_server_init=yes
+  ac_cv_lib_mysqlclient_r_mysql_reconnect=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-ac_cv_lib_mysqlclient_r_mysql_server_init=no
+ac_cv_lib_mysqlclient_r_mysql_reconnect=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlclient_r_mysql_server_init" >&5
-echo "${ECHO_T}$ac_cv_lib_mysqlclient_r_mysql_server_init" >&6
-if test $ac_cv_lib_mysqlclient_r_mysql_server_init = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBMYSQLCLIENT_R 1
-_ACEOF
+echo "$as_me:$LINENO: result: $ac_cv_lib_mysqlclient_r_mysql_reconnect" >&5
+echo "${ECHO_T}$ac_cv_lib_mysqlclient_r_mysql_reconnect" >&6
+if test $ac_cv_lib_mysqlclient_r_mysql_reconnect = yes; then
 
-  LIBS="-lmysqlclient_r $LIBS"
+        MYSQL_LIB_SPEC="${MYSQL_LIB_SPEC} -lmysqlclient_r"
 
 else
 
-  { { echo "$as_me:$LINENO: error: \"cannot find a working mysqlclient library\"" >&5
+        echo "$as_me:$LINENO: checking for mysql_reconnect in -lmysql_client" >&5
+echo $ECHO_N "checking for mysql_reconnect in -lmysql_client... $ECHO_C" >&6
+if test "${ac_cv_lib_mysql_client_mysql_reconnect+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmysql_client  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char mysql_reconnect ();
+int
+main ()
+{
+mysql_reconnect ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_mysql_client_mysql_reconnect=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_mysql_client_mysql_reconnect=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_mysql_client_mysql_reconnect" >&5
+echo "${ECHO_T}$ac_cv_lib_mysql_client_mysql_reconnect" >&6
+if test $ac_cv_lib_mysql_client_mysql_reconnect = yes; then
+
+            MYSQL_LIB_SPEC="${MYSQL_LIB_SPEC} -lmysql_client"
+
+else
+
+            { { echo "$as_me:$LINENO: error: \"cannot find a working mysqlclient library\"" >&5
 echo "$as_me: error: \"cannot find a working mysqlclient library\"" >&2;}
    { (exit 1); exit 1; }; }
 
 fi
 
+
+fi
+
+fi
 LDFLAGS="${TDBCMSYQL_SAVED_LDFLAGS}"
 
     vars="${MYSQL_LIB_SPEC}"
