Changed configurator so that 8.6 no longer requires a dummy tclooConfig.h

diff --git a/tdbcodbc/configure b/tdbcodbc/configure
--- a/tdbcodbc/configure
+++ b/tdbcodbc/configure
@@ -2384,6 +2384,27 @@ _ACEOF
 
 
 
+#--------------------------------------------------------------------
+# Load the tclooConfig.sh file on Tcl versions where oo is an
+# extension.
+#--------------------------------------------------------------------
+
+if test "${TCL_MAJOR_VERSION}" -lt 8 ; then
+    { { echo "$as_me:$LINENO: error: ${PACKAGE_NAME} ${PACKAGE_VERSION} requires Tcl 8.5 or newer.
+Found configuration for Tcl ${TCL_VERSION}." >&5
+echo "$as_me: error: ${PACKAGE_NAME} ${PACKAGE_VERSION} requires Tcl 8.5 or newer.
+Found configuration for Tcl ${TCL_VERSION}." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test "${TCL_MAJOR_VERSION}" -eq 8 ; then
+  if test "${TCL_MINOR_VERSION}" -lt 5 ; then
+    { { echo "$as_me:$LINENO: error: ${PACKAGE_NAME} ${PACKAGE_VERSION} requires Tcl 8.5 or newer.
+Found configuration for Tcl ${TCL_VERSION}." >&5
+echo "$as_me: error: ${PACKAGE_NAME} ${PACKAGE_VERSION} requires Tcl 8.5 or newer.
+Found configuration for Tcl ${TCL_VERSION}." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  if test "${TCL_MINOR_VERSION}" -eq 5 ; then
 
     #
     # Ok, lets find the tcloo configuration
@@ -2534,6 +2555,10 @@ echo "$as_me: WARNING: Found Makefile - using build library specs for tcloo" >&2
 
 
 
+  else
+    TCLOO_CFLAGS='-DUSE_TCLOO_STUBS'
+  fi
+fi
 
 
     #
@@ -8263,15 +8288,41 @@ echo "$as_me: error: could not find header file '${srcdir}/$i'" >&2;}
     done
 
 
+if test "${TCL_MAJOR_VERSION}" -eq 8 ; then
+  if test "${TCL_MINOR_VERSION}" -eq 5 ; then
 
-    vars="${TCLOO_INCLUDE_SPEC} ${TDBC_INCLUDE_SPEC} ${ODBC_INCLUDE_SPEC}"
+    vars="${TCLOO_INCLUDE_SPEC}"
     for i in $vars; do
 	PKG_INCLUDES="$PKG_INCLUDES $i"
     done
 
 
 
-    vars="${TCLOO_STUB_LIB_SPEC} ${TDBC_STUB_LIB_SPEC} ${ODBC_LIB_SPEC}"
+    vars="${TCLOO_STUB_LIB_SPEC}"
+    for i in $vars; do
+	if test "${TEA_PLATFORM}" = "windows" -a "$GCC" = "yes" ; then
+	    # Convert foo.lib to -lfoo for GCC.  No-op if not *.lib
+	    i=`echo "$i" | sed -e 's/^\([^-].*\)\.lib$/-l\1/i'`
+	fi
+	PKG_LIBS="$PKG_LIBS $i"
+    done
+
+
+  fi
+fi
+
+    PKG_CFLAGS="$PKG_CFLAGS ${TCLOO_CFLAGS}"
+
+
+
+    vars="${TDBC_INCLUDE_SPEC} ${ODBC_INCLUDE_SPEC}"
+    for i in $vars; do
+	PKG_INCLUDES="$PKG_INCLUDES $i"
+    done
+
+
+
+    vars="${TDBC_STUB_LIB_SPEC} ${ODBC_LIB_SPEC}"
     for i in $vars; do
 	if test "${TEA_PLATFORM}" = "windows" -a "$GCC" = "yes" ; then
 	    # Convert foo.lib to -lfoo for GCC.  No-op if not *.lib
@@ -8282,7 +8333,7 @@ echo "$as_me: error: could not find header file '${srcdir}/$i'" >&2;}
 
 
 
-    PKG_CFLAGS="$PKG_CFLAGS ${TCLOO_CFLAGS} ${TDBC_CFLAGS}"
+    PKG_CFLAGS="$PKG_CFLAGS ${TDBC_CFLAGS}"
 
 
 
