another try at autoconf for odbcinst

diff --git a/tdbcodbc/configure b/tdbcodbc/configure
--- a/tdbcodbc/configure
+++ b/tdbcodbc/configure
@@ -8218,7 +8218,7 @@ fi
 { echo "$as_me:$LINENO: result: $ac_cv_header_odbcinst_h" >&5
 echo "${ECHO_T}$ac_cv_header_odbcinst_h" >&6; }
 if test $ac_cv_header_odbcinst_h = yes; then
-  :
+  HAVE_ODBCINST=1
 else
   cat >>confdefs.h <<\_ACEOF
 #define NO_ODBCINST 1
@@ -8395,13 +8395,13 @@ fi
     done
 
 
-{ echo "$as_me:$LINENO: checking for strlen in -lodbcinst" >&5
-echo $ECHO_N "checking for strlen in -lodbcinst... $ECHO_C" >&6; }
-if test "${ac_cv_lib_odbcinst_strlen+set}" = set; then
+{ echo "$as_me:$LINENO: checking for strlen in -lodbccp32" >&5
+echo $ECHO_N "checking for strlen in -lodbccp32... $ECHO_C" >&6; }
+if test "${ac_cv_lib_odbccp32_strlen+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
   ac_check_lib_save_LIBS=$LIBS
-LIBS="-lodbcinst $PKG_LIBS $LIBS"
+LIBS="-lodbccp32 $PKG_LIBS $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -8442,23 +8442,97 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
 	 test ! -s conftest.err
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
-  ac_cv_lib_odbcinst_strlen=yes
+  ac_cv_lib_odbccp32_strlen=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-	ac_cv_lib_odbcinst_strlen=no
+	ac_cv_lib_odbccp32_strlen=no
 fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
 LIBS=$ac_check_lib_save_LIBS
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_lib_odbcinst_strlen" >&5
-echo "${ECHO_T}$ac_cv_lib_odbcinst_strlen" >&6; }
-if test $ac_cv_lib_odbcinst_strlen = yes; then
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_odbccp32_strlen" >&5
+echo "${ECHO_T}$ac_cv_lib_odbccp32_strlen" >&6; }
+if test $ac_cv_lib_odbccp32_strlen = yes; then
 
-    eval "ODBCINST_LIB_SPEC=\"-lodbcinst\""
+    eval "ODBCINST_LIB_SPEC=\"-lodbccp32\""
+
+else
+
+   { echo "$as_me:$LINENO: checking for strlen in -lodbccp" >&5
+echo $ECHO_N "checking for strlen in -lodbccp... $ECHO_C" >&6; }
+if test "${ac_cv_lib_odbccp_strlen+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lodbccp $PKG_LIBS $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char strlen ();
+int
+main ()
+{
+return strlen ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_odbccp_strlen=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_odbccp_strlen=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_odbccp_strlen" >&5
+echo "${ECHO_T}$ac_cv_lib_odbccp_strlen" >&6; }
+if test $ac_cv_lib_odbccp_strlen = yes; then
+
+        eval "ODBCINST_LIB_SPEC=\"-lodbccp\""
+
+fi
+
+
+fi
+
+if test x"${HAVE_ODBCINST}" != x ; then
     TDBCODBC_SAVED_LIBS="${LIBS}"
     LIBS="${ODBCINST_LIB_SPEC} ${ODBC_LIB_SPEC} ${LIBS}"
     { echo "$as_me:$LINENO: checking for Unicode interface to odbcinst" >&5
@@ -8514,9 +8588,7 @@ fi
 
 rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
       conftest$ac_exeext conftest.$ac_ext
-
 fi
-
 TDBCODBC_SAVED_LIBS="${LIBS}"
 
     vars="${ODBCINST_LIB_SPEC}"
