* tdbc/configure.in: Changed configuration to use TEA_PATH_CONFIG to * tdbc/aclocal.m4:   locate tcloo and tdbc.  Removed the local code that                      did it from aclocal.m4. * tdbc/configure:    Autoconf 2.61
* tdbcodbc/configure.in: Changed configuration to use TEA_PATH_CONFIG to
* tdbcodbc/aclocal.m4:   locate tcloo and tdbc.  Removed the local code that 
	                 did it from aclocal.m4.
* tdbcodbc/configure:    Autoconf 2.61

diff --git a/tdbc/configure b/tdbc/configure
--- a/tdbc/configure
+++ b/tdbc/configure
@@ -675,13 +675,14 @@ TCL_DEFS
 TCL_EXTRA_CFLAGS
 TCL_LD_FLAGS
 TCL_SHLIB_LD_LIBS
-TCLOO_VERSION
-TCLOO_BIN_DIR
-TCLOO_LIB_SPEC
-TCLOO_STUB_LIB_SPEC
-TCLOO_INCLUDE_SPEC
-TCLOO_PRIVATE_INCLUDE_SPEC
-TCLOO_CFLAGS
+tcloo_VERSION
+tcloo_BIN_DIR
+tcloo_SRC_DIR
+tcloo_LIB_FILE
+tcloo_LIB_SPEC
+tcloo_STUB_LIB_FILE
+tcloo_STUB_LIB_SPEC
+tcloo_STUB_LIB_PATH
 CC
 CFLAGS
 LDFLAGS
@@ -1326,8 +1327,7 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-tcl              directory containing tcl configuration
                           (tclConfig.sh)
-  --with-tcloo            directory containing TclOO configuration
-                          (tclooConfig.sh)
+  --with-tcloo              directory containing tcloo configuration (tclooConfig.sh)
   --with-tclinclude       directory containing the public Tcl header files
   --with-celib=DIR        use Windows/CE support library from DIR
 
@@ -2141,7 +2141,7 @@ echo "${ECHO_T}could not find ${TCL_BIN_DIR}/tclConfig.sh" >&6; }
 
 
     #
-    # Ok, lets find the tclOO configuration
+    # Ok, lets find the tcloo configuration
     # First, look for one uninstalled.
     # the alternative search directory is invoked by --with-tcloo
     #
@@ -2155,14 +2155,14 @@ if test "${with_tcloo+set}" = set; then
   withval=$with_tcloo; with_tclooconfig=${withval}
 fi
 
-	{ echo "$as_me:$LINENO: checking for TclOO configuration" >&5
-echo $ECHO_N "checking for TclOO configuration... $ECHO_C" >&6; }
+	{ echo "$as_me:$LINENO: checking for tcloo configuration" >&5
+echo $ECHO_N "checking for tcloo configuration... $ECHO_C" >&6; }
 	if test "${ac_cv_c_tclooconfig+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
 
 
-	    # First check to see if --with-tclooconfig was specified.
+	    # First check to see if --with-tcloo was specified.
 	    if test x"${with_tclooconfig}" != x ; then
 		case ${with_tclooconfig} in
 		    */tclooConfig.sh )
@@ -2170,7 +2170,7 @@ else
 			    { echo "$as_me:$LINENO: WARNING: --with-tcloo argument should refer to directory containing tclooConfig.sh, not to tclooConfig.sh itself" >&5
 echo "$as_me: WARNING: --with-tcloo argument should refer to directory containing tclooConfig.sh, not to tclooConfig.sh itself" >&2;}
 			    with_tclooconfig=`echo ${with_tclooconfig} | sed 's!/tclooConfig\.sh$!!'`
-			fi ;;
+			fi;;
 		esac
 		if test -f "${with_tclooconfig}/tclooConfig.sh" ; then
 		    ac_cv_c_tclooconfig=`(cd ${with_tclooconfig}; pwd)`
@@ -2181,23 +2181,36 @@ echo "$as_me: error: ${with_tclooconfig} directory doesn't contain tclooConfig.s
 		fi
 	    fi
 
-	    # then check for a private TclOO library
+	    # then check for a private tcloo installation
 	    if test x"${ac_cv_c_tclooconfig}" = x ; then
 		for i in \
-			../oo \
-			`ls -dr ../TclOO[0-1].[0-9].[0-9]* 2>/dev/null` \
-			`ls -dr ../TclOO[0-1].[0-9] 2>/dev/null` \
-			`ls -dr ../TclOO[0-1].[0-9]* 2>/dev/null` \
-			../../oo \
-			`ls -dr ../../TclOO[0-1].[0-9].[0-9]* 2>/dev/null` \
-			`ls -dr ../../TclOO[0-1].[0-9] 2>/dev/null` \
-			`ls -dr ../../TclOO[0-1].[0-9]* 2>/dev/null` \
-			../../../oo \
-			`ls -dr ../../../TclOO[0-1].[0-9].[0-9]* 2>/dev/null` \
-			`ls -dr ../../../TclOO[0-1].[0-9] 2>/dev/null` \
-			`ls -dr ../../../TclOO[0-1].[0-9]* 2>/dev/null` ; do
+			../tcloo \
+			`ls -dr ../tcloo*[0-9].[0-9]*.[0-9]* 2>/dev/null` \
+			`ls -dr ../tcloo*[0-9].[0-9][0-9] 2>/dev/null` \
+			`ls -dr ../tcloo*[0-9].[0-9] 2>/dev/null` \
+			`ls -dr ../tcloo*[0-9].[0-9]* 2>/dev/null` \
+			../../tcloo \
+			`ls -dr ../../tcloo*[0-9].[0-9]*.[0-9]* 2>/dev/null` \
+			`ls -dr ../../tcloo*[0-9].[0-9][0-9] 2>/dev/null` \
+			`ls -dr ../../tcloo*[0-9].[0-9] 2>/dev/null` \
+			`ls -dr ../../tcloo*[0-9].[0-9]* 2>/dev/null` \
+			../../../tcloo \
+			`ls -dr ../../../tcloo*[0-9].[0-9]*.[0-9]* 2>/dev/null` \
+			`ls -dr ../../../tcloo*[0-9].[0-9][0-9] 2>/dev/null` \
+			`ls -dr ../../../tcloo*[0-9].[0-9] 2>/dev/null` \
+			`ls -dr ../../../tcloo*[0-9].[0-9]* 2>/dev/null` \
+			${srcdir}/../tcloo \
+			`ls -dr ${srcdir}/../tcloo*[0-9].[0-9]*.[0-9]* 2>/dev/null` \
+			`ls -dr ${srcdir}/../tcloo*[0-9].[0-9][0-9] 2>/dev/null` \
+			`ls -dr ${srcdir}/../tcloo*[0-9].[0-9] 2>/dev/null` \
+			`ls -dr ${srcdir}/../tcloo*[0-9].[0-9]* 2>/dev/null` \
+			; do
 		    if test -f "$i/tclooConfig.sh" ; then
 			ac_cv_c_tclooconfig=`(cd $i; pwd)`
+			break
+		    fi
+		    if test -f "$i/unix/tclooConfig.sh" ; then
+			ac_cv_c_tclooconfig=`(cd $i/unix; pwd)`
 			break
 		    fi
 		done
@@ -2205,13 +2218,7 @@ echo "$as_me: error: ${with_tclooconfig} directory doesn't contain tclooConfig.s
 
 	    # check in a few common install locations
 	    if test x"${ac_cv_c_tclooconfig}" = x ; then
-		for i in `ls -d ${libdir}/TclOO[0-1].* 2>/dev/null` \
-			`ls -d ${exec_prefix}/lib/TclOO[0-1].* 2>/dev/null` \
-			`ls -d ${prefix}/lib/TclOO[0-1].* 2>/dev/null` \
-			`ls -d /usr/local/lib/TclOO[0-1].* 2>/dev/null` \
-			`ls -d /usr/contrib/lib/TclOO[0-1].* 2>/dev/null` \
-			`ls -d /usr/lib/TclOO[0-1].* 2>/dev/null` \
-                        `ls -d ${libdir} 2>/dev/null` \
+		for i in `ls -d ${libdir} 2>/dev/null` \
 			`ls -d ${exec_prefix}/lib 2>/dev/null` \
 			`ls -d ${prefix}/lib 2>/dev/null` \
 			`ls -d /usr/local/lib 2>/dev/null` \
@@ -2225,71 +2232,51 @@ echo "$as_me: error: ${with_tclooconfig} directory doesn't contain tclooConfig.s
 		done
 	    fi
 
-	    # TEA specific: on Windows, check in common installation locations
-	    if test "${TEA_PLATFORM}" = "windows" \
-		-a x"${ac_cv_c_tclooconfig}" = x ; then
-		for i in `ls -d C:/Tcl/lib/TclOO[0-1].* 2>/dev/null` \
-			`ls -d C:/Progra~1/Tcl/lib/TclOO[0-1].* 2>/dev/null` \
-                        `ls -d C:/Tcl/lib 2>/dev/null` \
-			`ls -d C:/Progra~1/Tcl/lib 2>/dev/null` \
-			; do
-		    if test -f "$i/tclooConfig.sh" ; then
-			ac_cv_c_tclooconfig=`(cd $i; pwd)`
-			break
-		    fi
-		done
-	    fi
-
-	    # check in a few other private locations
-	    if test x"${ac_cv_c_tclooconfig}" = x ; then
-		for i in \
-			${srcdir}/../tcloo \
-			`ls -dr ${srcdir}/../TclOO[0-1].[0-9].[0-9]* 2>/dev/null` \
-			`ls -dr ${srcdir}/../TclOO[0-1].[0-9] 2>/dev/null` \
-			`ls -dr ${srcdir}/../TclOO[0-1].[0-9]* 2>/dev/null` ; do
-		    if test -f "$i/tclooConfig.sh" ; then
-			ac_cv_c_tclooconfig=`(cd $i; pwd)`
-			break
-		    fi
-		done
-	    fi
-
 fi
 
 
 	if test x"${ac_cv_c_tclooconfig}" = x ; then
-	    TCLOO_BIN_DIR="# no TclOO configs found"
-	    { echo "$as_me:$LINENO: WARNING: Can't find TclOO configuration definitions" >&5
-echo "$as_me: WARNING: Can't find TclOO configuration definitions" >&2;}
+	    tcloo_BIN_DIR="# no tcloo configs found"
+	    { echo "$as_me:$LINENO: WARNING: Cannot find tcloo configuration definitions" >&5
+echo "$as_me: WARNING: Cannot find tcloo configuration definitions" >&2;}
 	    exit 0
 	else
 	    no_tcloo=
-	    TCLOO_BIN_DIR=${ac_cv_c_tclooconfig}
-	    { echo "$as_me:$LINENO: result: found ${TCLOO_BIN_DIR}/tclooConfig.sh" >&5
-echo "${ECHO_T}found ${TCLOO_BIN_DIR}/tclooConfig.sh" >&6; }
+	    tcloo_BIN_DIR=${ac_cv_c_tclooconfig}
+	    { echo "$as_me:$LINENO: result: found $tcloo_BIN_DIR/tclooConfig.sh" >&5
+echo "${ECHO_T}found $tcloo_BIN_DIR/tclooConfig.sh" >&6; }
 	fi
     fi
 
 
-    { echo "$as_me:$LINENO: checking for existence of ${TCLOO_BIN_DIR}/tclooConfig.sh" >&5
-echo $ECHO_N "checking for existence of ${TCLOO_BIN_DIR}/tclooConfig.sh... $ECHO_C" >&6; }
+    { echo "$as_me:$LINENO: checking for existence of ${tcloo_BIN_DIR}/tclooConfig.sh" >&5
+echo $ECHO_N "checking for existence of ${tcloo_BIN_DIR}/tclooConfig.sh... $ECHO_C" >&6; }
 
-    if test -f "${TCLOO_BIN_DIR}/tclooConfig.sh" ; then
+    if test -f "${tcloo_BIN_DIR}/tclooConfig.sh" ; then
         { echo "$as_me:$LINENO: result: loading" >&5
 echo "${ECHO_T}loading" >&6; }
-	. "${TCLOO_BIN_DIR}/tclooConfig.sh"
+	. "${tcloo_BIN_DIR}/tclooConfig.sh"
     else
-        { echo "$as_me:$LINENO: result: could not find ${TCLOO_BIN_DIR}/tclooConfig.sh" >&5
-echo "${ECHO_T}could not find ${TCLOO_BIN_DIR}/tclooConfig.sh" >&6; }
+        { echo "$as_me:$LINENO: result: file not found" >&5
+echo "${ECHO_T}file not found" >&6; }
     fi
 
-    # eval is required to do the TCLOO_DBGX substitution
-    eval "TCLOO_STUB_LIB_FILE=\"${TCLOO_STUB_LIB_FILE}\""
+    #
+    # If the tcloo_BIN_DIR is the build directory (not the install directory),
+    # then set the common variable name to the value of the build variables.
+    # For example, the variable tcloo_LIB_SPEC will be set to the value
+    # of tcloo_BUILD_LIB_SPEC. An extension should make use of tcloo_LIB_SPEC
+    # instead of tcloo_BUILD_LIB_SPEC since it will work with both an
+    # installed and uninstalled version of Tcl.
+    #
 
-    # eval is required to do the TCLOO_DBGX substitution
-    eval "TCLOO_LIB_SPEC=\"${TCLOO_LIB_SPEC}\""
-    eval "TCLOO_STUB_LIB_FLAG=\"${TCLOO_STUB_LIB_FLAG}\""
-    eval "TCLOO_STUB_LIB_SPEC=\"${TCLOO_STUB_LIB_SPEC}\""
+    if test -f "${tcloo_BIN_DIR}/Makefile" ; then
+	{ echo "$as_me:$LINENO: WARNING: Found Makefile - using build library specs for tcloo" >&5
+echo "$as_me: WARNING: Found Makefile - using build library specs for tcloo" >&2;}
+        tcloo_LIB_SPEC=${tcloo_BUILD_LIB_SPEC}
+        tcloo_STUB_LIB_SPEC=${tcloo_BUILD_STUB_LIB_SPEC}
+        tcloo_STUB_LIB_PATH=${tcloo_BUILD_STUB_LIB_PATH}
+    fi
 
 
 
@@ -2298,7 +2285,8 @@ echo "${ECHO_T}could not find ${TCLOO_BIN_DIR}/tclooConfig.sh" >&6; }
 
 
 
-    # TEA specific:
+
+
 
 
 
@@ -11662,13 +11650,14 @@ TCL_DEFS!$TCL_DEFS$ac_delim
 TCL_EXTRA_CFLAGS!$TCL_EXTRA_CFLAGS$ac_delim
 TCL_LD_FLAGS!$TCL_LD_FLAGS$ac_delim
 TCL_SHLIB_LD_LIBS!$TCL_SHLIB_LD_LIBS$ac_delim
-TCLOO_VERSION!$TCLOO_VERSION$ac_delim
-TCLOO_BIN_DIR!$TCLOO_BIN_DIR$ac_delim
-TCLOO_LIB_SPEC!$TCLOO_LIB_SPEC$ac_delim
-TCLOO_STUB_LIB_SPEC!$TCLOO_STUB_LIB_SPEC$ac_delim
-TCLOO_INCLUDE_SPEC!$TCLOO_INCLUDE_SPEC$ac_delim
-TCLOO_PRIVATE_INCLUDE_SPEC!$TCLOO_PRIVATE_INCLUDE_SPEC$ac_delim
-TCLOO_CFLAGS!$TCLOO_CFLAGS$ac_delim
+tcloo_VERSION!$tcloo_VERSION$ac_delim
+tcloo_BIN_DIR!$tcloo_BIN_DIR$ac_delim
+tcloo_SRC_DIR!$tcloo_SRC_DIR$ac_delim
+tcloo_LIB_FILE!$tcloo_LIB_FILE$ac_delim
+tcloo_LIB_SPEC!$tcloo_LIB_SPEC$ac_delim
+tcloo_STUB_LIB_FILE!$tcloo_STUB_LIB_FILE$ac_delim
+tcloo_STUB_LIB_SPEC!$tcloo_STUB_LIB_SPEC$ac_delim
+tcloo_STUB_LIB_PATH!$tcloo_STUB_LIB_PATH$ac_delim
 CC!$CC$ac_delim
 CFLAGS!$CFLAGS$ac_delim
 LDFLAGS!$LDFLAGS$ac_delim
@@ -11696,7 +11685,6 @@ LIBOBJS!$LIBOBJS$ac_delim
 DL_LIBS!$DL_LIBS$ac_delim
 CFLAGS_DEBUG!$CFLAGS_DEBUG$ac_delim
 CFLAGS_OPTIMIZE!$CFLAGS_OPTIMIZE$ac_delim
-CFLAGS_WARNING!$CFLAGS_WARNING$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -11738,6 +11726,7 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+CFLAGS_WARNING!$CFLAGS_WARNING$ac_delim
 STLIB_LD!$STLIB_LD$ac_delim
 SHLIB_LD!$SHLIB_LD$ac_delim
 SHLIB_LD_LIBS!$SHLIB_LD_LIBS$ac_delim
@@ -11761,7 +11750,7 @@ CONFIGURE_OUTPUTS!$CONFIGURE_OUTPUTS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 21; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 22; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
