Changed to make the TDBC base module buildable on 8.6 without needing a dummy tclooConfig.sh

diff --git a/tdbc/configure b/tdbc/configure
--- a/tdbc/configure
+++ b/tdbc/configure
@@ -2139,6 +2139,27 @@ echo "${ECHO_T}could not find ${TCL_BIN_DIR}/tclConfig.sh" >&6; }
 #TEA_PATH_TKCONFIG
 #TEA_LOAD_TKCONFIG
 
+#--------------------------------------------------------------------
+# Load the tclooConfig.sh file on Tcl versions where oo is an
+# extension.
+#--------------------------------------------------------------------
+
+if test "${TCL_MAJOR_VERSION}" -lt 8 ; then
+    { { echo "$as_me:$LINENO: error: ${PACKAGE_NAME} ${PACKAGE_VERSION} requires Tcl 8.5 or newer.
+Found configuration for Tcl ${TCL_VERSION}." >&5
+echo "$as_me: error: ${PACKAGE_NAME} ${PACKAGE_VERSION} requires Tcl 8.5 or newer.
+Found configuration for Tcl ${TCL_VERSION}." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test "${TCL_MAJOR_VERSION}" -eq 8 ; then
+  if test "${TCL_MINOR_VERSION}" -lt 5 ; then
+    { { echo "$as_me:$LINENO: error: ${PACKAGE_NAME} ${PACKAGE_VERSION} requires Tcl 8.5 or newer.
+Found configuration for Tcl ${TCL_VERSION}." >&5
+echo "$as_me: error: ${PACKAGE_NAME} ${PACKAGE_VERSION} requires Tcl 8.5 or newer.
+Found configuration for Tcl ${TCL_VERSION}." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+  if test "${TCL_MINOR_VERSION}" -eq 5 ; then
 
     #
     # Ok, lets find the tcloo configuration
@@ -2289,6 +2310,8 @@ echo "$as_me: WARNING: Found Makefile - using build library specs for tcloo" >&2
 
 
 
+  fi
+fi
 
 #-----------------------------------------------------------------------
 # Handle the --prefix=... option by defaulting to what Tcl gave.
@@ -6841,6 +6864,8 @@ echo "$as_me: error: could not find header file '${srcdir}/$i'" >&2;}
     done
 
 
+if test "${TCL_MAJOR_VERSION}" -eq 8 ; then
+  if test "${TCL_MINOR_VERSION}" -eq 5 ; then
 
     vars="${TCLOO_INCLUDE_SPEC}"
     for i in $vars; do
@@ -6863,6 +6888,8 @@ echo "$as_me: error: could not find header file '${srcdir}/$i'" >&2;}
     PKG_CFLAGS="$PKG_CFLAGS ${TCLOO_CFLAGS}"
 
 
+  fi
+fi
 
     vars="tdbcStubLib.c"
     for i in $vars; do
